### PR TITLE
Serve all the public directory

### PR DESCRIPTION
**Pull request by Swizz**
The command `artisan serve` needs to serve all the public directory for delivering assets.

The second commit needs to be tested on a real HHVM server.
It was built only thanks to documentations.

Kind regards,

### CODE REVIEW

**Comment by mlntn** [comment]
The command currently follows its sister command in laravel/framework. What is the use case that requires these changes?

**Comment by Swizz** [comment]
In [laravel/laravel](/laravel/laravel) the `server.php` file is in the root of the project.
So, when the docroot option is not given, the server do not deliver the right file when the server file return false.

The php server is probably seeking around the base path.

**Comment by mlntn** [comment]
Ahh, I get it. Okay, I'll merge.

**Comment by mlntn** [comment]
Thanks!

**Pull request merged**
